# Generated by Serenay Mobile Deploy. The app runs the beta, release and
# fetch_locales lanes; the rest of this file is yours to change.
default_platform(:android)

platform :android do
  private_lane :build_aab do
{{PREPARE}}
  end

  desc "Internal testing"
  lane :beta do
    build_aab
    upload_to_play_store(
      track: "internal",{{AAB_ARG}}
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Google Play production"
  lane :release do
    require "json"
    require "tmpdir"

    text = ENV["WHATS_NEW"].to_s
    translations = JSON.parse(ENV["WHATS_NEW_TRANSLATIONS"] || "{}")
    locales = ENV["STORE_LOCALES_ANDROID"].to_s.split(",").map(&:strip).reject(&:empty?)

    build_aab

    # supply reads changelogs only from metadata folders. A fresh folder holds exactly
    # the store's languages, so no leftover folder can add a new language to the app.
    Dir.mktmpdir do |metadata|
      locales.each do |locale|
        dir = File.join(metadata, locale, "changelogs")
        FileUtils.mkdir_p(dir)
        File.write(File.join(dir, "default.txt"), translations[locale] || text)
      end

      upload_to_play_store(
        track: "production",{{AAB_ARG}}
        metadata_path: metadata,
        skip_upload_metadata: true,
        skip_upload_changelogs: locales.empty?,
        skip_upload_images: true,
        skip_upload_screenshots: true
      )
    end
  end

  desc "Prints the app's Google Play languages as FASTLANE_LOCALES=..."
  lane :fetch_locales do
    require "google/apis/androidpublisher_v3"
    require "googleauth"

    package_name = CredentialsManager::AppfileConfig.try_fetch_value(:package_name)
    json_key = CredentialsManager::AppfileConfig.try_fetch_value(:json_key_file)
    UI.user_error!("Google Play service account key not found: #{json_key}") unless json_key && File.exist?(json_key)

    service = Google::Apis::AndroidpublisherV3::AndroidPublisherService.new
    service.authorization = Google::Auth::ServiceAccountCredentials.make_creds(
      json_key_io: File.open(json_key),
      scope: "https://www.googleapis.com/auth/androidpublisher"
    )

    begin
      edit = service.insert_edit(package_name)
    rescue Google::Apis::ClientError => e
      raise unless e.status_code == 404
      puts "FASTLANE_APP_NOT_FOUND"
      next
    end

    locales = (service.list_edit_listings(package_name, edit.id).listings || []).map(&:language).uniq.sort
    service.delete_edit(package_name, edit.id) rescue nil
    puts "FASTLANE_LOCALES=#{locales.join(',')}"
  end
end
