# Generated by Serenay Mobile Deploy. The app runs the beta, release and
# fetch_locales lanes; the rest of this file is yours to change.
default_platform(:android)

platform :android do
{{LANES}}
end
