# Generated by Serenay Mobile Deploy. The app runs the beta, release and
# fetch_locales lanes; the rest of this file is yours to change.
default_platform(:ios)

platform :ios do
  before_all do
    if ENV["ASC_KEY_ID"] && ENV["ASC_ISSUER_ID"] && ENV["ASC_PRIVATE_KEY"]
      app_store_connect_api_key(
        key_id: ENV["ASC_KEY_ID"],
        issuer_id: ENV["ASC_ISSUER_ID"],
        key_content: ENV["ASC_PRIVATE_KEY"],
        is_key_content_base64: false,
        in_house: false
      )
    end
  end

  private_lane :build_ipa do
{{PREPARE}}
    build_app(
      {{BUILD_ARGS}},
      clean: true,
      xcargs: "-allowProvisioningUpdates",
      export_xcargs: "-allowProvisioningUpdates"
    )
  end

  desc "TestFlight"
  lane :beta do
    build_ipa
    upload_to_testflight
  end

  desc "App Store"
  lane :release do
    require "json"

    text = ENV["WHATS_NEW"].to_s
    translations = JSON.parse(ENV["WHATS_NEW_TRANSLATIONS"] || "{}")
    locales = ENV["STORE_LOCALES_IOS"].to_s.split(",").map(&:strip).reject(&:empty?)

    build_ipa
    deliver(
      force: true,
      skip_screenshots: true,
      skip_metadata: locales.empty?,
      release_notes: locales.to_h { |locale| [locale, translations[locale] || text] },
      precheck_include_in_app_purchases: false,
      automatic_release: true,
      submit_for_review: true,
      submission_information: { add_id_info_uses_idfa: false }
    )
  end

  desc "Prints the app's App Store languages as FASTLANE_LOCALES=..."
  lane :fetch_locales do
    UI.user_error!("App Store Connect API key is not configured") unless Spaceship::ConnectAPI.token

    app = Spaceship::ConnectAPI::App.find(CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier))
    if app.nil?
      puts "FASTLANE_APP_NOT_FOUND"
      next
    end

    version = app.get_app_store_versions(filter: { platform: "IOS" }).first
    UI.user_error!("The app has no App Store version yet") unless version

    puts "FASTLANE_LOCALES=#{version.get_app_store_version_localizations.map(&:locale).uniq.sort.join(',')}"
  end
end
